import { Link } from 'react-router-dom';
import PageHeader from '../../components/PageHeader.jsx';
import LoadingState from '../../components/LoadingState.jsx';
import ErrorState from '../../components/ErrorState.jsx';
import StatusBadge from '../../components/StatusBadge.jsx';
import { profileApi } from '../../services/api.js';
import { useAsync } from '../../hooks/useAsync.js';

export default function ProfilePage() {
  const { data, loading, error, execute } = useAsync(profileApi.get);
  if (loading) return <LoadingState label="Loading your profile…" />;
  if (error) return <ErrorState message={error} onRetry={() => execute()} />;
  const { user, stats, courseProgress } = data;
  return <div className="profile-page page-stack"><PageHeader eyebrow="Student profile" title="Your learning profile." description="A simple view of your account, assigned level, and learning activity." /><section className="profile-hero"><div className="profile-avatar-large">{user.fullName.slice(0, 1).toUpperCase()}</div><div><span className="eyebrow">Student account</span><h2>{user.fullName}</h2><p>{user.email}</p></div><StatusBadge tone="blue">{user.assignedLevel} · Assigned level</StatusBadge></section><div className="profile-grid"><section className="profile-card"><div className="section-heading"><div><span className="eyebrow">Overview</span><h2>Account details</h2></div></div><div className="profile-fields"><div><span>Full name</span><strong>{user.fullName}</strong></div><div><span>Email address</span><strong>{user.email}</strong></div><div><span>Authentication</span><strong>{user.authProvider === 'both' ? 'Email & Google' : user.authProvider}</strong></div><div><span>Assigned Japanese level</span><strong>{user.assignedLevel}</strong></div></div><p className="locked-note">Your assigned level is controlled by the level determination system.</p></section><section className="profile-card"><div className="section-heading"><div><span className="eyebrow">Learning statistics</span><h2>Your activity</h2></div></div><div className="profile-stat-list"><div><span>Completed tests</span><strong>{stats.completedTests}</strong></div><div><span>Courses started</span><strong>{stats.coursesStarted}</strong></div><div><span>Passed levels</span><strong>{user.passedLevels.join(' · ') || '—'}</strong></div></div></section></div><section className="profile-card course-progress-card"><div className="section-heading"><div><span className="eyebrow">Course progress</span><h2>Learning materials in motion</h2></div></div>{courseProgress.length ? <div className="profile-course-list">{courseProgress.map((progress) => <div key={progress._id}><div><strong>{progress.courseId?.title}</strong><small>{progress.courseId?.level}</small></div><div className="profile-course-progress"><div className="progress-track"><span style={{ width: `${progress.progressPercent}%` }} /></div><strong>{progress.progressPercent}%</strong></div></div>)}</div> : <p className="muted-text">Start a course to see your progress here.</p>}</section><section className="profile-card settings-card"><div className="section-heading"><div><span className="eyebrow">Account settings</span><h2>Keep your access secure.</h2></div></div><div className="settings-row"><div><strong>Password recovery</strong><p>Request a reset link if you need to update your password.</p></div><Link className="button button-secondary" to="/forgot-password">Reset password</Link></div><div className="settings-row"><div><strong>Assigned level</strong><p>Your level cannot be changed manually.</p></div><StatusBadge tone="blue">System controlled</StatusBadge></div></section></div>;
}
